version: "3.8"

services:
  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: sh -c "cd main &&
             python -m celery -A main worker"
    depends_on:
      - redis

  web:
    build: .
    command:
      sh -c "python main/manage.py send_email &&
             python main/manage.py runserver 0.0.0.0:8000"
#      volumes:
#        - ./project/report:/app/project/report
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - celery
